Leaderboard - Project Setup
MaiRizk/Leaderboard pull request #1
Opened 2021-09-10 14:33 UTC by MaiRizk

I have created an npm project with Webpack. 
The project is written with HTML and CSS only. 
This repo is built using Gitflow

2021-09-10 15:08 UTC, george-shammar requested changes
Hi @MaiRizk , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project without a README.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-09-10 17:13 UTC, Georjane requested changes
### Hello, Team @MaiRizk, ✋🏽 

Good job so far! You have a very professional Readme file, your PR is professional and you have a good mastery of git-flow. Your linters are all passing, I applaud that too.
However, we have a few more changes to make in order to meet all requirements for this project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-10 17:13 UTC, Georjane commented on package.json
> +    "yamljs": "^0.3.0"
- [ ] All webpack related packages should be included in package.json like `webpack`, `webpack-cli`, `webpack-dev-server` etc. Also, those packages should be added as devDependencies. You are missing `webpack-dev-server`

2021-09-10 17:13 UTC, Georjane commented on package.json
> +  },
- [ ] npm run build throws an error. See the error below. Please fix this.
```
$ npm run build

> leaderboard@1.0.0 build
> webpack

[webpack-cli] Failed to load 'C:\Users\PC\Desktop\TSE\Leaderboard\webpack.config.js' config
[webpack-cli] Error: Cannot find module 'html-webpack-plugin'

```
- [ ] Also your npm should run scripts like the following. It does not need to be exact as long as there is a way to start the project say `npm run start`
```
  "scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack --config webpack.config.js --watch"
  }
```

2021-09-11 00:28 UTC, carlos-ssh approved these changes
Hi @MaiRizk , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 00:30 UTC, merged